# Generated by Django 4.2.5 on 2023-09-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_item_estoque_pedidoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='itens',
        ),
    ]
