# Generated by Django 4.2.5 on 2023-09-28 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_pedido_data_criacao_pedido_data_vencimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_vencimento',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 5, 17, 13, 19, 67828)),
        ),
    ]
