# Generated by Django 4.2.5 on 2023-09-28 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_pedido_cancelado_alter_pedido_data_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_vencimento',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 5, 18, 55, 0, 416939)),
        ),
    ]
